### ISSUE TITLE
Markdown syntax highlighting confused by indented code block

### ISSUE THREAD

**Issue by r0polach** [geany/geany#2797]
Geany's markdown syntax highlighting (without the markdown plugin) is confused, when code block is indented.
All the text after code block end is blue and ignores *all following* markdown syntax highlighting .
![md_indented_code_block](https://user-images.githubusercontent.com/1393254/114905882-c0be4c80-9e19-11eb-8ebe-3d5bfc41b439.png)

When code block is *not* indented, everything is ok.

**Comment by rdipardo** [comment]
@nomadbyte,

> Apparently, using tilde-delimited code blocks within a list seems to work ok

"Seems" is exactly right: those lines are being styled like ~~strikeout~~ because of a false match with the first two `~~`s:

![Screenshot_2021-06-27_23-27-37](https://user-images.githubusercontent.com/59004801/123575229-4d34a600-d79f-11eb-9980-6bd0bf377b4f.png)

Triple `~~~`s are recognized as code fences only when they're flush with the margin and the previous line is blank:

![Screenshot_2021-06-27_23-19-07](https://user-images.githubusercontent.com/59004801/123574962-ce3f6d80-d79e-11eb-82c2-dd69004f46c4.png)


_Note on the colorscheme; it's [Delt Dark](https://github.com/geany/geany-themes/blob/master/colorschemes/delt-dark.conf)_

**Comment by rdipardo** [comment]
Patched upstream: https://github.com/ScintillaOrg/lexilla/commit/78c09310c52cfc6659c006d3f6650f252d4a3955

![Screenshot_2021-06-30_03-15-34](https://user-images.githubusercontent.com/59004801/123918094-87de4000-d951-11eb-891a-13830164d4a0.png)

**Comment by rdipardo** [comment]
:warning: Look for it _after_ v5.1.1; that one's buggy: https://github.com/geany/geany/issues/1439#issuecomment-896544368 :warning:

**Comment by eht16** [comment]
Since we already use Scintilla 5.1.5 where this bug is fixed, I'll close this issue.

Just re-open if you disagree.

**Comment by r0polach** [comment]
Is the fix included in latest release 1.38?
Because I still see the wrong highlighting in this version.

**Comment by eht16** [comment]
It is *not* included in 1.38, it is fixed in GIT master and this will be included in the next release.
