### ISSUE TITLE
Word completion truncated

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#702]
![wordcompletiontruncated](https://cloud.githubusercontent.com/assets/7548378/10593532/7e9e5334-76bc-11e5-949e-f04a742b1cd7.png)

When I push the text size up to the limit using <b>control+mouse wheel</b> and then do a word completion, the choice seem to be truncated.

**Comment by elextr** [comment]
Confirmed on
08:59:15: Geany INFO		: Geany 1.26 (git >= 31325bb), en_AU.UTF-8
08:59:15: Geany INFO		: GTK 3.10.8, GLib 2.40.2

@philiprbrenan and others, please always provide version of Geany and GTK and Glib on reports, the easiest is to paste the two lines shown above from the top of menu->help->debug messages.

If anyone has the latest scite please see if the same occurs there.

**Comment by codebrainz** [comment]
I think this was fixed just recently:

http://sourceforge.net/p/scintilla/code/ci/4133f6b50b7d7d335528cce91a6b2e8aa56109a4/

Should be in Geany when Scintilla is next released/updated.

**Comment by elextr** [comment]
@codebrainz AFAICT that patch is in the version I used above with Scintilla 3.6.1.

**Comment by elextr** [comment]
Further investigation shows that the autocomplete box is wrong the first time after <ctrl>-wheel zooming, but then is right after that.  If you zoom up its too small, if you zoom down its too big.

@b4n, I understand you did some work on this, any thoughts?

**Comment by b4n** [comment]
I can confirm indeed.  I'll see to this (although it's clearly an upstream Scintilla bug)

> @b4n, I understand you did some work on this, any thoughts?

Not exactly, I worked on styling and various size computation for the popup itself, but not on each row of the tree view.  But I should be able to figure it out and probably fix it.

**Comment by b4n** [comment]
Fix submitted upstream in https://sourceforge.net/p/scintilla/bugs/1774/

> Confirmed on
08:59:15: Geany INFO : Geany 1.26 (git >= 31325bb), en_AU.UTF-8
08:59:15: Geany INFO : GTK 3.10.8, GLib 2.40.2

On GTK3 it was fixed by the 3.6.1 update, e.g. in 04ef30ea06982865cf6ba097e5c6f630f2a554bf

**Comment by elextr** [comment]
@b4n, Scintilla 3.6.1 is in current master (at least my `version.txt` says 361), but the problem still occurs on GTK3, maybe its GTK version dependent?

**Comment by b4n** [comment]
@elextr hum, odd then, must indeed depend on the GTK version…  I'll have to check.

**Comment by elextr** [comment]
Sorry, hasn't fixed GTK3.

14:29:53: Geany INFO		: Geany 1.26 (git >= 31325bb), en_AU.UTF-8
14:29:53: Geany INFO		: GTK 3.10.8, GLib 2.40.2

**Comment by elextr** [comment]
Effects of zooming on the autocomplete in Geany (as above) are shown below.

Notes that might help solve:

1. happens only on the first autocomplete shown after zooming, all subsequent autocompletes are fine
2. happens irrespective of the method used to zoom, mouse wheel, key shortcut, menu.

@b4n, if you still can't reproduce tell me what to look at for more info.

![zoom text smaller](https://cloud.githubusercontent.com/assets/811085/11171128/da9233ea-8c33-11e5-81c5-94ad62e7ba85.png)
![zoom text larger](https://cloud.githubusercontent.com/assets/811085/11171129/da9376c4-8c33-11e5-862c-d30642452c89.png)

**Comment by kugel-** [comment]
Works for me as of now.

20:48:43: Geany INFO		: Geany 1.32 (git >= 5791cde21), de_DE.utf8
20:48:43: Geany INFO		: GTK 3.22.29, GLib 2.56.0

**Comment by b4n** [comment]
Interestingly I still see the "wrong the first time" behavior when *de*zooming on GTK3, but for zooming it work for me (both GTK2 and GTK3).

Can anybody still reproduce?

**Comment by elextr** [comment]
I see same as @b4n on GTK3, first autocomplete after zoom out uses same size dialog as last time, so may contain blank space, but don't see the OP too small problem.

**Comment by elextr** [comment]
@kugel- I think this is still a valid problem, both @b4n and I last posted various situations where we see it.

**Comment by kugel-** [comment]
Please remove the pending timeout label next time.

**Comment by elextr** [comment]
@kugel- you just closed it, no message why or anything, and a 3 month old bug confirmed should not have to be fixed in some arbitrary time limit.
